version: '3.8'
services:
  app:
    build: .
    #command: bash -c 'while !</dev/tcp/db/5432; do sleep 1; done; uvicorn app.main:app
    command: "uvicorn app.main:app --host 0.0.0.0"
    ports:
      - 8000:8000
    depends_on:
      - database
    networks:
      - app-network

  database:
    image:  postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      - DATABASE_HOST=127.0.0.1
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=secreto
      - POSTGRES_DB=shoppingCart

networks:
  app-network:
    driver: bridge